export const DEVELOPER_KEYWORDS = [
    // Universal Terms & Tools
    '#devsky',
    // Version Control
    'github',
    'gitlab',
    'bitbucket',
    'mercurial',
    'perforce',

    // Package Managers
    'npm',
    'yarn',
    'pnpm',
    'cargo',
    'maven',
    'gradle',
    'cocoapods',
    'bundler',
    'homebrew',

    // IDEs & Editors
    'vscode',
    'intellij',
    'webstorm',
    'pycharm',
    'eclipse',
    'androidstudio',
    'xcode',
    'vim',
    'neovim',
    'emacs',
    'sublimetext',
    'notepad++',

    // Container & Orchestration
    'docker',
    'kubernetes',
    'k8s',
    'podman',
    'containerd',
    'openshift',
    'rancher',
    'helm',
    'docker-compose',

    // Programming Languages
    // General Purpose
    'typescript',
    'javascript',
    'python',
    'java',
    'kotlin',
    'swift',
    'golang',
    'rustlang',
    'php',
    'scala',
    'csharp',
    'fsharp',
    'cpp',
    'c++',
    'objective-c',
    'objectivec',
    'perl',
    'lua',
    'haskell',
    'erlang',
    'elixir',
    'clojure',
    'groovy',
    'julia',
    'matlab',
    'fortran',
    'cobol',
    'pascal',
    'prolog',
    'lisp',
    'racket',
    'ocaml',
    'purescript',
    'reason',
    'crystal',
    'nim',
    'zig',
    'vlang',
    'solidity',
    'assemblyscript',
    'wasm',
    'webassembly',

    // Frameworks & Libraries
    // Frontend
    'react',
    'vue',
    'angular',
    'svelte',
    'solid',
    'preact',
    'nextjs',
    'nuxtjs',
    'astro',
    'qwik',
    'gatsby',
    'jquery',
    'backbone',
    'ember',
    'alpine',
    'lit',
    'stencil',
    'tailwind',
    'materialui',
    'chakraui',
    'antdesign',
    'storybook',

    // Backend
    'nodejs',
    'deno',
    'nestjs',
    'springboot',
    'django',
    'fastapi',
    'rails',
    'laravel',
    'symfony',
    'aspnet',
    'dotnet',
    'actix',
    'axum',
    'phoenix',
    'playframework',
    'quarkus',
    'micronaut',

    // Mobile
    'reactnative',
    'ionic',
    'xamarin',
    'nativescript',
    'kivy',
    'androidjetpack',
    'swiftui',
    'kotlinmultiplatform',

    // Game Development
    'unrealengine',
    'godot',
    'gamemaker',
    'cocos2d',
    'phaser',
    'babylonjs',
    'threejs',
    'playcanvas',
    'pico8',
    'libgdx',
    'monogame',

    // Data Science & ML
    'tensorflow',
    'pytorch',
    'keras',
    'scikitlearn',
    'pandas',
    'numpy',
    'jupyter',
    'rapids',
    'opencv',
    'spark',
    'hadoop',
    'kubeflow',
    'mlflow',
    
    // English Terms
    // Basic Titles (existing plus new)
    'Software Developer',
    'Software Engineer',
    'Frontend Developer',
    'Front-end Developer',
    'Front End Developer',
    'Backend Developer',
    'Back-end Developer',
    'Back End Developer',
    'Full Stack Developer',
    'Full-Stack Developer',
    'Fullstack Developer',
    'DevOps Engineer',
    'Site Reliability Engineer',
    'Cloud Engineer',
    'Mobile Developer',
    'iOS Developer',
    'Android Developer',
    'Web Developer',
    'API Developer',
    'Database Developer',
    'ML Engineer',
    'Security Engineer',
    'Platform Engineer',

    // Game Development Roles
    'Game Developer',
    'Game Programmer',
    'Engine Programmer',
    'Graphics Programmer',
    'Gameplay Programmer',
    'Physics Programmer',
    'Network Programmer',
    'Tools Programmer',
    'Game Client Developer',
    'Game Server Developer',

    // Embedded/IoT Roles
    'Embedded Developer',
    'Embedded Engineer',
    'IoT Developer',
    'IoT Engineer',
    'Firmware Developer',
    'Firmware Engineer',
    'Hardware Engineer',
    'FPGA Developer',
    'FPGA Engineer',
    'Systems Programmer',
    'Device Driver Developer',
    'Real-time Systems Engineer',
    'Microcontroller Programmer',

    // Data/ML Roles
    'Data Engineer',
    'Data Scientist',
    'Machine Learning Engineer',
    'ML Ops Engineer',
    'AI Engineer',
    'Deep Learning Engineer',
    'Research Engineer',
    'Computer Vision Engineer',
    'NLP Engineer',
    'Analytics Engineer',
    'Data Architect',
    'Big Data Engineer',

    // Security Roles
    'Security Engineer',
    'Security Researcher',
    'Penetration Tester',
    'Security Analyst',
    'Cryptographer',
    'Application Security Engineer',
    'Cloud Security Engineer',
    'Security Architect',
    'Malware Analyst',
    'Threat Researcher',

    // French Terms (existing plus new)
    'Développeur Logiciel',
    'Développeuse Logiciel',
    'Ingénieur Logiciel',
    'Ingénieure Logiciel',
    'Développeur de Jeux',
    'Développeuse de Jeux',
    'Développeur Embarqué',
    'Développeuse Embarquée',
    'Ingénieur IoT',
    'Ingénieure IoT',
    'Développeur Firmware',
    'Développeuse Firmware',
    'Scientifique des Données',
    'Ingénieur IA',
    'Ingénieure IA',
    'Ingénieur Sécurité',
    'Ingénieure Sécurité',
    'Développeur Blockchain',
    'Développeuse Blockchain',

    // German Terms (existing plus new)
    'Spieleentwickler',
    'Spieleentwicklerin',
    'Embedded Entwickler',
    'Embedded Entwicklerin',
    'IoT Entwickler',
    'IoT Entwicklerin',
    'Firmware Entwickler',
    'Firmware Entwicklerin',
    'KI Ingenieur',
    'KI Ingenieurin',
    'Datenwissenschaftler',
    'Datenwissenschaftlerin',
    'Sicherheitsingenieur',
    'Sicherheitsingenieurin',
    'Blockchain Entwickler',
    'Blockchain Entwicklerin',

    // Japanese Terms (existing plus new)
    'ゲーム開発者',
    'ゲームプログラマー',
    '組込みエンジニア',
    '組み込みエンジニア',
    'IoTエンジニア',
    'ファームウェアエンジニア',
    'データサイエンティスト',
    '機械学習エンジニア',
    'AIエンジニア',
    'セキュリティエンジニア',
    'ブロックチェーンエンジニア',
    'デバイスドライバー開発者',
    'システムプログラマー',

    // Spanish Terms (existing plus new)
    'Desarrollador de Juegos',
    'Desarrolladora de Juegos',
    'Desarrollador Embebido',
    'Desarrolladora Embebida',
    'Ingeniero IoT',
    'Ingeniera IoT',
    'Desarrollador de Firmware',
    'Desarrolladora de Firmware',
    'Científico de Datos',
    'Científica de Datos',
    'Ingeniero de IA',
    'Ingeniera de IA',
    'Ingeniero de Seguridad',
    'Ingeniera de Seguridad',
    'Desarrollador Blockchain',
    'Desarrolladora Blockchain',

    // Chinese Terms
    '软件工程师',
    '前端工程师',
    '后端工程师',
    '全栈工程师',
    '游戏开发工程师',
    '嵌入式工程师',
    'IoT工程师',
    '固件工程师',
    '数据科学家',
    '机器学习工程师',
    '人工智能工程师',
    '安全工程师',
    '区块链工程师',
    '系统程序员',
    '设备驱动开发工程师',

    // Korean Terms
    '소프트웨어 엔지니어',
    '프론트엔드 개발자',
    '백엔드 개발자',
    '풀스택 개발자',
    '게임 개발자',
    '임베디드 개발자',
    'IoT 엔지니어',
    '펌웨어 엔지니어',
    '데이터 사이언티스트',
    '머신러닝 엔지니어',
    '인공지능 엔지니어',
    '보안 엔지니어',
    '블록체인 개발자',
    '시스템 프로그래머',
    '디바이스 드라이버 개발자',

    // Technical Domains & Concepts
    // Cloud Native
    'Serverless',
    'FaaS',
    'PaaS',
    'IaaS',
    'SaaS',
    'Cloud Native',
    'Microservices',
    'Service Mesh',
    'Edge Computing',
    'Fog Computing',
    'Cloud Computing',
    'Distributed Systems',
    'Event Driven',
    'Event Sourcing',
    'CQRS',
    'Message Queue',
    'Stream Processing',

    // Embedded/IoT
    'RTOS',
    'Bare Metal',
    'Firmware',
    'Microcontroller',
    'SoC',
    'FPGA',
    'ARM',
    'AVR',
    'PIC',
    'Arduino',
    'Raspberry Pi',
    'ESP32',
    'ESP8266',
    'Zigbee',
    'BLE',
    'LoRaWAN',
    'MQTT',
    'CoAP',

    // Game Development
    'Game Loop',
    'Game Engine',
    'Physics Engine',
    'Rendering Engine',
    'Vertex Shader',
    'Fragment Shader',
    'Geometry Shader',
    'Compute Shader',
    'Ray Tracing',
    'Path Tracing',
    'Rasterization',
    'Collision Detection',
    'Animation System',
    'Particle System',
    'Level Editor',
    'Pathfinding',
    'Networking',
    'Client-Server',
    'P2P Gaming',
    'Game State',
    'Entity Component System',
    'ECS',

    // Security
    'Cryptography',
    'Encryption',
    'Hash Function',
    'Digital Signature',
    'PKI',
    'TLS',
    'SSL',
    'HTTPS',
    'SSH',
    'Firewall',
    'SIEM',
    'Pentesting',
    'Red Team',
    'Blue Team',
    'Purple Team',
    'Vulnerability Assessment',
    'Threat Modeling',
    'Zero Trust',
    'OWASP',
    'AppSec',
    'DevSecOps',

    // Extended Technical Concepts
    'API Gateway',
    'Load Balancer',
    'Reverse Proxy',
    'Forward Proxy',
    'CDN',
    'DNS',
    'DHCP',
    'VPC',
    'SDN',
    'BGP',
    'OSPF',
    'VLAN',
    'SDR',
    'WebRTC',
    'WebSocket',
    'WebAssembly',
    'WASI',
    'SSR',
    'SSG',
    'ISR',
    'PWA',
    'SPA',
    'MPA',
    'JAMstack',
    'MEAN',
    'MERN',
] as const;